version: '3.8'

services:

    php:
        image: php:8.4-cli
        container_name: balancer_php
        volumes:
            - .:/app
        working_dir: /app
        command: php -S 0.0.0.0:8000 -t public
        ports:
            - "8000:8000"

    redis:
        image: redis:7
        container_name: balancer_redis
        ports:
            - "6379:6379"
